name: Train Model CI

on:
  push:
    paths:
      - 'modelling.py'
      - 'MLProject'
      - 'conda.yaml'
      - '.github/workflows/train_model.yml'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MLflow & deps
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project
        run: |
          mlflow run workflow-CI/MLproject --entry-point main --env-manager=local
          
      - name: Commit model artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add workflow-CI/artifacts/model
          git commit -m "Auto commit: model artifacts from CI"
          git push